const ActionTypes = {
    RECIEVE_RAW_CONFIGITEMS: 'RECIEVE_RAW_CONFIGITEMS',
    RECIEVE_REMOVED_CONFIGITEM: 'RECIEVE_REMOVED_CONFIGITEM',
    RECIEVE_UPDATED_CONFIGITEM: 'RECIEVE_UPDATED_CONFIGITEM',  
    RECIEVE_APPFILTER: 'RECIEVE_APPFILTER',
    CLEAR_REMOVED_CONFIGITEM: 'CLEAR_REMOVED_CONFIGITEM'
  };
  
  export default ActionTypes;